### ISSUE TITLE
Error when going to module configuration page

### ISSUE THREAD

**Issue by Zmove** [vdomah/oc-mailtranslatable-plugin#1]
Hello,

Very good idea to give us the possibility to translate emails. Unfortunately, I get an error when I go to the module configuration page :

SQLSTATE[HY000]: General error: 1 no such function: CONCAT_WS (SQL: select "vdomah_mailtranslatable_templates".*, (select CONCAT_WS(' ', code, subject) from "system_mail_templates" where "vdomah_mailtranslatable_templates"."mail_template_id" = "system_mail_templates"."id") as "mail_template" from "vdomah_mailtranslatable_templates" order by "mail_template" desc)

I think it's because I use SQLite database, not sure that CONCAT_WS exists.

Best regards,

Alex

**Comment by vdomah** [comment]
Hi, 
Thanks for your request. Fixed that problem in new version.
